# Generated by Django 6.0.4 on 2026-08-27 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('org_affiliation', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('VOLUNTEER', 'Volunteer')], default='EMPLOYEE', max_length=16)),
                ('employment_status', models.CharField(blank=True, max_length=64)),
                ('municipality', models.CharField(choices=[('Agdangan', 'Agdangan'), ('Alabat', 'Alabat'), ('Atimonan', 'Atimonan'), ('Buenavista', 'Buenavista'), ('Burdeos', 'Burdeos'), ('Calauag', 'Calauag'), ('Candelaria', 'Candelaria'), ('Catanauan', 'Catanauan'), ('Dolores', 'Dolores'), ('General Luna', 'General Luna'), ('General Nakar', 'General Nakar'), ('Guinayangan', 'Guinayangan'), ('Gumaca', 'Gumaca'), ('Infanta', 'Infanta'), ('Jomalig', 'Jomalig'), ('Lopez', 'Lopez'), ('Lucban', 'Lucban'), ('Lucena City', 'Lucena City'), ('Macalelon', 'Macalelon'), ('Mauban', 'Mauban'), ('Mulanay', 'Mulanay'), ('Padre Burgos', 'Padre Burgos'), ('Pagbilao', 'Pagbilao'), ('Panukulan', 'Panukulan'), ('Patnanungan', 'Patnanungan'), ('Perez', 'Perez'), ('Pitogo', 'Pitogo'), ('Plaridel', 'Plaridel'), ('Polillo', 'Polillo'), ('Quezon', 'Quezon'), ('Real', 'Real'), ('Sampaloc', 'Sampaloc'), ('San Andres', 'San Andres'), ('San Antonio', 'San Antonio'), ('San Francisco', 'San Francisco'), ('San Narciso', 'San Narciso'), ('Sariaya', 'Sariaya'), ('Tagkawayan', 'Tagkawayan'), ('Tayabas City', 'Tayabas City'), ('Tiaong', 'Tiaong'), ('Unisan', 'Unisan')], max_length=32)),
                ('other_drr_training', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['municipality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_key', models.CharField(choices=[('ICS_L1', 'Basic Incident Command System Level 1'), ('ICS_L2', 'ICS — Integrated Planning Level 2'), ('ICS_L3', 'ICS — Position Course Level 3'), ('ICS_L4', 'ICS — All Hazard Incident Management Team Level 4'), ('ICS_TFI', 'ICS — Training for Instructors'), ('ICS_EXEC', 'Incident Command System – Executive Course'), ('EOC', 'Emergency Operations Center (EOC)'), ('EOC_EXEC', 'Emergency Operations Center – Executive Course'), ('RDANA', 'Rapid Damage Assessment & Needs Analysis (RDANA)'), ('CBDRRM', 'Community-Based Disaster Risk Reduction and Management'), ('CBDRRM_TOT', 'Community-Based Disaster Risk Reduction and Management – Training of Trainers'), ('ECCDIE', 'Early Childhood Care & Development in Emergencies Training (ECCDiE)'), ('CP', 'Contingency Plan Training'), ('PSCP', 'Public Service Continuity Plan (PSCP)'), ('LDRRMP', 'Local Disaster Risk Reduction and Management Plan Training (LDRRMP)'), ('BLS', 'Basic Life Support (BLS)'), ('SFA', 'Standard First Aid (SFA)'), ('BLS_TOF', 'Basic Life Support Learning Facilitation Course (BLS-TOF)'), ('CVERT', 'Crash Vehicle Extrication and Rescue Training (CVERT)'), ('WASAR', 'Water Search and Rescue Training (WASAR)'), ('SWAR', 'Swift Water Rescue Training (SWAR)'), ('BRRT', 'Basic Rope Rescue Training (BRRT)'), ('MOSART', 'Mountain Search & Rescue Training (MOSART)'), ('MOSAR_TOT', 'Mountain Search & Rescue Training of Trainers (MOSAR TOT)'), ('HAZMAT_AWARENESS', 'Hazardous Materials Awareness Level'), ('HAZMAT_OPERATIONS', 'Hazardous Materials Operations Level'), ('CSSR', 'Collapsed Structure Search & Rescue Training (CSSR)')], max_length=32)),
                ('year_attained', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2035)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='core.personnel')),
            ],
            options={
                'ordering': ['training_key'],
                'constraints': [models.UniqueConstraint(fields=('personnel', 'training_key'), name='uniq_personnel_training_key')],
            },
        ),
    ]
