# Generated by Django 6.0.4 on 2026-08-31 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personnel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_rosters', to='core.personnel')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_attendees', to='core.trainingschedule')),
            ],
            options={
                'ordering': ['personnel__name'],
                'unique_together': {('training', 'personnel')},
            },
        ),
    ]
