# Generated by Django 6.0.4 on 2026-09-01 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_personnelattendee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'REGISTERED')), fields=('training', 'user'), name='uniq_active_registration_per_user'),
        ),
    ]
